name: Bug Report
description: Report a problem with the Grab OTP extension
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Edge
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: What version of Grab OTP are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to website...
        2. Click extension icon...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs (if any)
      description: |
        If you see any error messages in the browser console (F12), please include them here.
        **Important**: Do not include any personal information like email addresses or OTP codes.
      render: text

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      options:
        - Always
        - Sometimes
        - Rarely
        - First time
    validations:
      required: true