name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like the extension to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternatively, it could...

  - type: dropdown
    id: browser-scope
    attributes:
      label: Browser Scope
      description: Which browsers should this feature support?
      multiple: true
      options:
        - Chrome
        - Firefox  
        - Both browsers
        - Browser agnostic
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Significantly needed
        - Critical - Blocking current usage
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature in practice
      placeholder: When I visit banking websites, I want to...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Check any that apply to your feature request
      options:
        - label: This feature should maintain current security standards
          required: true
        - label: This feature should not require additional permissions
        - label: This feature should work without internet connection
        - label: This feature should be optional/configurable